actions:
  mv_to_chrome_folder: mkdir $(find ~/.mozilla/firefox/ -name '*dev-edition-default')/chrome
    && ln -s $HOME/.mozilla/firefox/userC* $(find ~/.mozilla/firefox/ -name '*dev-edition-default')/chrome
config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  longkey: false
dotfiles:
  d_hooks:
    dst: ~/.config/pacman/hooks
    src: config/pacman/hooks
  d_snippets:
    dst: ~/.config/nvim/snippets
    src: config/nvim/snippets
  f_alacritty.yml:
    dst: ~/.config/alacritty/alacritty.yml
    src: config/alacritty/alacritty.yml
  f_chrome-flags.conf:
    dst: ~/.config/chrome-flags.conf
    src: config/chrome-flags.conf
  f_config:
    dst: ~/.config/i3/config
    src: config/i3/config
  f_config.lua:
    dst: ~/.imapfilter/config.lua
    src: imapfilter/config.lua
    trans:
    - gpg
  f_dircolors:
    dst: ~/.dircolors
    src: dircolors
  f_dunstrc:
    dst: ~/.config/dunst/dunstrc
    src: config/dunst/dunstrc
  f_git-pass-mapping.ini:
    dst: ~/.config/pass-git-helper/git-pass-mapping.ini
    src: config/pass-git-helper/git-pass-mapping.ini
  f_gitconfig:
    dst: ~/.gitconfig
    src: gitconfig
  f_gpg-agent.conf:
    dst: ~/.gnupg/gpg-agent.conf
    src: gnupg/gpg-agent.conf
  f_gpg.conf:
    dst: ~/.gnupg/gpg.conf
    src: gnupg/gpg.conf
  f_gpg.rc:
    dst: ~/.mutt/gpg.rc
    src: mutt/gpg.rc
  f_hub:
    dst: ~/.config/hub
    src: config/hub
    trans:
    - gpg
  f_ideavimrc:
    dst: ~/.ideavimrc
    src: ideavimrc
  f_init.vim:
    dst: ~/.config/nvim/init.vim
    src: config/nvim/init.vim
  f_macros:
    dst: ~/.mutt/macros
    src: mutt/macros
  f_mail.sh:
    dst: ~/documents/cron/mail.sh
    src: documents/cron/mail.sh
  f_mailcap:
    dst: ~/.mutt/mailcap
    src: mutt/mailcap
  f_mailcount.sh:
    dst: ~/.config/i3/mailcount.sh
    src: config/i3/mailcount.sh
  f_makepkg.conf:
    dst: ~/.config/pacman/makepkg.conf
    src: config/pacman/makepkg.conf
  f_mutt-alias:
    dst: ~/.mutt-alias
    src: mutt-alias
    trans:
    - gpg
  f_mutt-colors-solarized-dark-16.muttrc:
    dst: ~/.mutt/mutt-colors-solarized-dark-16.muttrc
    src: mutt/mutt-colors-solarized-dark-16.muttrc
  f_muttrc:
    dst: ~/.muttrc
    src: muttrc
    trans:
    - gpg
  f_notmuch-config:
    dst: ~/.notmuch-config
    src: notmuch-config
    trans:
    - gpg
  f_offlineimaprc:
    dst: ~/.offlineimaprc
    src: offlineimaprc
    trans:
    - gpg
  f_passmenu.sh:
    dst: ~/.config/i3/passmenu.sh
    src: config/i3/passmenu.sh
  f_redshift.conf:
    dst: ~/.config/redshift.conf
    src: config/redshift.conf
  f_screenlayout-home.sh:
    dst: ~/.config/i3/screenlayout-home.sh
    src: config/i3/screenlayout-home.sh
  f_screenlayout-office.sh:
    dst: ~/.config/i3/screenlayout-office.sh
    src: config/i3/screenlayout-office.sh
  f_settings.xml:
    dst: ~/.m2/settings.xml
    src: m2/settings.xml
    trans:
    - gpg
  f_siren-bordeaux.sh:
    dst: ~/.screenlayout/siren-bordeaux.sh
    src: screenlayout/siren-bordeaux.sh
  f_status.toml:
    dst: ~/.config/i3/status.toml
    src: config/i3/status.toml
  f_tv.sh:
    dst: ~/.screenlayout/tv.sh
    src: screenlayout/tv.sh
  f_udiskie.service:
    dst: ~/.config/systemd/user/udiskie.service
    src: config/systemd/user/udiskie.service
  f_userchrome.css:
    actions:
    - mv_to_chrome_folder
    dst: ~/.mozilla/firefox/userChrome.css
    src: mozilla/firefox/userChrome.css
  f_usercontent.css:
    actions:
    - mv_to_chrome_folder
    dst: ~/.mozilla/firefox/userContent.css
    src: mozilla/firefox/userContent.css
  f_xinitrc:
    dst: ~/.xinitrc
    src: xinitrc
  f_xmodmap:
    dst: ~/.Xmodmap
    src: Xmodmap
  f_xserverrc:
    dst: ~/.xserverrc
    src: xserverrc
profiles:
  mars:
    dotfiles:
    - ALL
  troy:
    dotfiles:
    - ALL
trans:
  gpg: gpg -q --for-your-eyes-only --no-tty -d {0} > {1}
