icons = "awesome"
theme = "slick"

[[block]]
block = "custom"
command = "~/.config/i3/mailcount.sh"
on_click = "alacritty -t Neomutt -e neomutt"
#markup = "pango"

[[block]]
block = "maildir"
inboxes = [
	"/home/yfful/.mail/gmail/INBOX",
	"/home/yfful/.mail/gmail/Sindicetech",
	"/home/yfful/.mail/gmail/Sindicetech.Github",
	"/home/yfful/.mail/gmail/rust",
	"/home/yfful/.mail/gmail/rust.Github",
]

[[block]]
block = "toggle"
text = "office"
command_state = "xrandr | grep 'HDMI2 connected'"
command_off = "~/.config/i3/screenlayout-home.sh"
command_on = "~/.config/i3/screenlayout-office.sh"
interval = 5

[[block]]
block = "sound"
step_width = 3
on_click = "pavucontrol"

[[block]]
block = "battery"
device = "BAT1"
interval = 10
show = "both"

[[block]]
block = "net"
device = "wlp3s0"
ssid = true
speed_down = false
speed_up = false
interval = 5

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
