[icons]
icons = "awesome6"
[theme]
theme = "solarized-dark"

[[block]]
block = "custom"
command = "~/.config/i3/mailcount.sh"
json = true
[[block.click]]
button = "left"
cmd = "alacritty -t Neomutt -e neomutt"

[[block]]
block = "sound"
step_width = 3
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "temperature"

[[block]]
block = "battery"

[[block]]
block = "net"
device = "wlp3s0"
interval = 5

[[block]]
block = "disk_space"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "time"
interval = 60
format = "$icon $timestamp.datetime(f:'%a %d/%m %R')"

[[block]]
block = "bluetooth"
# kasia's headphones
#mac = "74:5C:4B:2B:19:07"
# my headphones
mac = "70:BF:92:F3:F0:1C"
